[window]

opacity = 1 

padding.x = 5 
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "JetBrainsMonoNL Nerd Font Mono"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
italic.family = "JetBrainsMonoNL Nerd Font Mono"
bold_italic.family = "JetBrainsMonoNL Nerd Font Mono"

size = 14.0

# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night Moon
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_moon.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff8d94'
green = '#c7fb6d'
yellow = '#ffd8ab'
blue = '#9ab8ff'
magenta = '#caabff'
cyan = '#b2ebff'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

# Colors (Tokyo Night Storm variant)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# # Default colors
# [colors.primary]
# background = '#24283b'
# foreground = '#a9b1d6'

# # Normal colors
# [colors.normal]
# black   = '#32344a'
# red     = '#f7768e'
# green   = '#9ece6a'
# yellow  = '#e0af68'
# blue    = '#7aa2f7'
# magenta = '#ad8ee6'
# cyan    = '#449dab'
# white   = '#9699a8'

# # Bright colors
# [colors.bright]
# black   = '#444b6a'
# red     = '#ff7a93'
# green   = '#b9f27c'
# yellow  = '#ff9e64'
# blue    = '#7da6ff'
# magenta = '#bb9af7'
# cyan    = '#0db9d7'
# white   = '#acb0d0'
