[ids]
*

[main]
capslock = overload(control, esc)
leftalt = layer(alt_layer)

[alt_layer:A]
space = swap(nav)

[nav]
a = 1
s = 2
d = 3
f = 4
g = 5
q = 6
w = 7
e = 8
r = 9
t = 0
h = left
j = down
k = up
l = right
